import type {
  Banner,
  Category,
  ContactInfo,
  GalleryImage,
  Product,
  Testimonial,
} from "./types";

const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const sampleCategories: Category[] = [
  {
    id: "cat-sofas",
    slug: "sofas",
    name: "Sofas",
    description: "Handcrafted sofas and sectionals for elegant living rooms.",
    image: img("photo-1555041469-a586c61ea9bc"),
    sort_order: 1,
  },
  {
    id: "cat-beds",
    slug: "beds",
    name: "Beds",
    description: "Solid wood and upholstered beds for restful nights.",
    image: img("photo-1505693416388-ac5ce068fe85"),
    sort_order: 2,
  },
  {
    id: "cat-dining",
    slug: "dining-tables",
    name: "Dining Tables",
    description: "Statement dining tables that bring family together.",
    image: img("photo-1617806118233-18e1de247200"),
    sort_order: 3,
  },
  {
    id: "cat-wardrobes",
    slug: "wardrobes",
    name: "Wardrobes",
    description: "Spacious wardrobes with smart storage solutions.",
    image: img("photo-1595428774223-ef52624120d2"),
    sort_order: 4,
  },
  {
    id: "cat-office",
    slug: "office-furniture",
    name: "Office Furniture",
    description: "Ergonomic desks and chairs for productive workspaces.",
    image: img("photo-1524758631624-e2822e304c36"),
    sort_order: 5,
  },
  {
    id: "cat-tv-units",
    slug: "tv-units",
    name: "TV Units",
    description: "Modern entertainment units and media consoles.",
    image: img("photo-1586023492125-27b2c045efd7"),
    sort_order: 6,
  },
  {
    id: "cat-chairs",
    slug: "chairs",
    name: "Chairs",
    description: "Accent, lounge and dining chairs in timeless designs.",
    image: img("photo-1592078615290-033ee584e267"),
    sort_order: 7,
  },
  {
    id: "cat-mattresses",
    slug: "mattresses",
    name: "Mattresses",
    description: "Orthopedic and memory-foam mattresses for deep sleep.",
    image: img("photo-1631049307264-da0ec9d70304"),
    sort_order: 8,
  },
];

const colours = ["Walnut", "Natural Oak", "Charcoal Grey", "Ivory", "Teak"];

export const sampleProducts: Product[] = [
  {
    id: "prod-1",
    slug: "aurelia-3-seater-sofa",
    name: "Aurelia 3-Seater Sofa",
    category_slug: "sofas",
    short_description: "Plush 3-seater with premium fabric upholstery.",
    description:
      "The Aurelia is a statement 3-seater sofa featuring deep, plush cushioning and a solid teak wood frame. Its clean lines and premium fabric make it the centerpiece of any modern living room.",
    material: "Solid teak frame, high-density foam, premium linen fabric",
    dimensions: 'W 210cm x D 92cm x H 85cm',
    colours: ["Ivory", "Charcoal Grey", "Teal"],
    images: [
      img("photo-1555041469-a586c61ea9bc"),
      img("photo-1550226891-ef816aed4a98"),
      img("photo-1493663284031-b7e3aefcae8e"),
    ],
    price_label: "On request",
    featured: true,
    in_stock: true,
    created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "prod-2",
    slug: "verona-l-shaped-sectional",
    name: "Verona L-Shaped Sectional",
    category_slug: "sofas",
    short_description: "Spacious L-shaped sectional with chaise lounge.",
    description:
      "A generously proportioned L-shaped sectional designed for lounging in style. The Verona offers a reversible chaise, feather-blend cushions and a durable hardwood base.",
    material: "Hardwood frame, feather-blend cushions, textured weave fabric",
    dimensions: "W 280cm x D 180cm x H 84cm",
    colours: ["Beige", "Charcoal Grey", "Olive"],
    images: [
      img("photo-1567016432779-094069958ea5"),
      img("photo-1550226891-ef816aed4a98"),
    ],
    price_label: "On request",
    featured: true,
    in_stock: true,
    created_at: "2024-01-12T00:00:00Z",
  },
  {
    id: "prod-3",
    slug: "kyoto-king-bed",
    name: "Kyoto King Platform Bed",
    category_slug: "beds",
    short_description: "Low-profile king bed in solid walnut.",
    description:
      "Inspired by Japanese minimalism, the Kyoto platform bed pairs a low-profile silhouette with a warm walnut finish and an upholstered headboard for understated luxury.",
    material: "Solid walnut, upholstered headboard",
    dimensions: "W 193cm x L 214cm x H 100cm (King)",
    colours: ["Walnut", "Natural Oak"],
    images: [
      img("photo-1505693416388-ac5ce068fe85"),
      img("photo-1522708323590-d24dbb6b0267"),
    ],
    price_label: "On request",
    featured: true,
    in_stock: true,
    created_at: "2024-01-14T00:00:00Z",
  },
  {
    id: "prod-4",
    slug: "haven-storage-bed",
    name: "Haven Upholstered Storage Bed",
    category_slug: "beds",
    short_description: "Queen bed with hydraulic storage.",
    description:
      "The Haven combines plush upholstery with a hydraulic lift-up base, offering generous hidden storage without compromising on comfort or style.",
    material: "Engineered wood, foam-padded fabric upholstery",
    dimensions: "W 165cm x L 205cm x H 110cm (Queen)",
    colours: ["Ivory", "Grey", "Navy"],
    images: [
      img("photo-1616594039964-ae9021a400a0"),
      img("photo-1522708323590-d24dbb6b0267"),
    ],
    price_label: "On request",
    featured: false,
    in_stock: true,
    created_at: "2024-01-16T00:00:00Z",
  },
  {
    id: "prod-5",
    slug: "olive-6-seater-dining-table",
    name: "Olive 6-Seater Dining Table",
    category_slug: "dining-tables",
    short_description: "Solid wood 6-seater dining table.",
    description:
      "A robust 6-seater dining table crafted from solid acacia with a natural live edge and powder-coated metal legs — perfect for family gatherings.",
    material: "Solid acacia wood, powder-coated steel legs",
    dimensions: "L 180cm x W 90cm x H 76cm",
    colours: ["Natural Oak", "Walnut"],
    images: [
      img("photo-1617806118233-18e1de247200"),
      img("photo-1592078615290-033ee584e267"),
    ],
    price_label: "On request",
    featured: true,
    in_stock: true,
    created_at: "2024-01-18T00:00:00Z",
  },
  {
    id: "prod-6",
    slug: "milano-8-seater-dining-set",
    name: "Milano 8-Seater Dining Set",
    category_slug: "dining-tables",
    short_description: "Grand dining set with upholstered chairs.",
    description:
      "The Milano dining set seats eight in comfort, featuring a marble-look tabletop and elegantly upholstered chairs for a refined dining experience.",
    material: "Sintered stone top, solid wood base, velvet chairs",
    dimensions: "L 220cm x W 100cm x H 76cm",
    colours: ["Ivory", "Charcoal Grey"],
    images: [img("photo-1615529182904-14819c35db37"), img("photo-1617806118233-18e1de247200")],
    price_label: "On request",
    featured: false,
    in_stock: true,
    created_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "prod-7",
    slug: "aspen-4-door-wardrobe",
    name: "Aspen 4-Door Wardrobe",
    category_slug: "wardrobes",
    short_description: "Spacious 4-door wardrobe with mirror.",
    description:
      "The Aspen offers four doors of organised storage, including a full-length mirror, soft-close hinges and adjustable shelving.",
    material: "Engineered wood, laminate finish, soft-close hardware",
    dimensions: "W 200cm x D 60cm x H 210cm",
    colours: ["Walnut", "Ivory", "Grey"],
    images: [img("photo-1595428774223-ef52624120d2"), img("photo-1558997519-83ea9252edf8")],
    price_label: "On request",
    featured: true,
    in_stock: true,
    created_at: "2024-01-22T00:00:00Z",
  },
  {
    id: "prod-8",
    slug: "sliding-2-door-wardrobe",
    name: "Nova Sliding 2-Door Wardrobe",
    category_slug: "wardrobes",
    short_description: "Space-saving sliding wardrobe.",
    description:
      "A sleek sliding-door wardrobe that saves floor space while offering a smart interior layout with drawers and hanging sections.",
    material: "Engineered wood, glass-panel sliding doors",
    dimensions: "W 180cm x D 62cm x H 220cm",
    colours: ["Charcoal Grey", "Natural Oak"],
    images: [img("photo-1558997519-83ea9252edf8"), img("photo-1595428774223-ef52624120d2")],
    price_label: "On request",
    featured: false,
    in_stock: true,
    created_at: "2024-01-24T00:00:00Z",
  },
  {
    id: "prod-9",
    slug: "executive-office-desk",
    name: "Regent Executive Office Desk",
    category_slug: "office-furniture",
    short_description: "Premium executive desk with storage.",
    description:
      "The Regent executive desk offers a spacious work surface, built-in cable management and lockable drawers, crafted for the modern professional.",
    material: "Engineered wood, veneer finish, metal accents",
    dimensions: "W 160cm x D 80cm x H 75cm",
    colours: ["Walnut", "Black Oak"],
    images: [img("photo-1524758631624-e2822e304c36"), img("photo-1497366216548-37526070297c")],
    price_label: "On request",
    featured: true,
    in_stock: true,
    created_at: "2024-01-26T00:00:00Z",
  },
  {
    id: "prod-10",
    slug: "ergo-mesh-office-chair",
    name: "Ergo Mesh Office Chair",
    category_slug: "office-furniture",
    short_description: "Ergonomic chair with lumbar support.",
    description:
      "Stay comfortable through long working hours with the Ergo mesh chair, featuring adjustable lumbar support, armrests and a breathable mesh back.",
    material: "Breathable mesh, nylon base, foam seat",
    dimensions: "W 66cm x D 66cm x H 118-128cm",
    colours: ["Black", "Grey"],
    images: [img("photo-1580480055273-228ff5388ef8"), img("photo-1592078615290-033ee584e267")],
    price_label: "On request",
    featured: false,
    in_stock: true,
    created_at: "2024-01-28T00:00:00Z",
  },
  {
    id: "prod-11",
    slug: "horizon-tv-unit",
    name: "Horizon Floating TV Unit",
    category_slug: "tv-units",
    short_description: "Wall-mounted TV unit with LED lighting.",
    description:
      "The Horizon floating TV unit combines a minimalist wall-mounted design with ambient LED lighting and ample storage for media devices.",
    material: "Engineered wood, matte laminate, LED strip",
    dimensions: "W 200cm x D 40cm x H 45cm",
    colours: ["Walnut", "Ivory", "Charcoal Grey"],
    images: [img("photo-1586023492125-27b2c045efd7"), img("photo-1616486338812-3dadae4b4ace")],
    price_label: "On request",
    featured: true,
    in_stock: true,
    created_at: "2024-01-30T00:00:00Z",
  },
  {
    id: "prod-12",
    slug: "cove-media-console",
    name: "Cove Media Console",
    category_slug: "tv-units",
    short_description: "Solid wood media console with drawers.",
    description:
      "A warm, solid-wood media console with fluted drawer fronts and brass handles, blending storage and style for your living space.",
    material: "Solid mango wood, brass hardware",
    dimensions: "W 150cm x D 45cm x H 55cm",
    colours: ["Natural Oak", "Walnut"],
    images: [img("photo-1616486338812-3dadae4b4ace"), img("photo-1586023492125-27b2c045efd7")],
    price_label: "On request",
    featured: false,
    in_stock: true,
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "prod-13",
    slug: "lisbon-accent-chair",
    name: "Lisbon Accent Chair",
    category_slug: "chairs",
    short_description: "Curved velvet accent chair.",
    description:
      "The Lisbon accent chair features a sculptural curved back, plush velvet upholstery and slim wooden legs — an elegant addition to any corner.",
    material: "Solid wood legs, velvet upholstery, foam padding",
    dimensions: "W 72cm x D 74cm x H 80cm",
    colours: ["Emerald", "Mustard", "Grey"],
    images: [img("photo-1592078615290-033ee584e267"), img("photo-1567538096630-e0c55bd6374c")],
    price_label: "On request",
    featured: true,
    in_stock: true,
    created_at: "2024-02-03T00:00:00Z",
  },
  {
    id: "prod-14",
    slug: "nordic-lounge-chair",
    name: "Nordic Lounge Chair",
    category_slug: "chairs",
    short_description: "Mid-century lounge chair with ottoman.",
    description:
      "A timeless mid-century lounge chair with a matching ottoman, offering supreme comfort with its moulded shell and leather cushions.",
    material: "Moulded plywood, genuine leather cushions",
    dimensions: "W 82cm x D 85cm x H 100cm",
    colours: ["Tan", "Black"],
    images: [img("photo-1567538096630-e0c55bd6374c"), img("photo-1592078615290-033ee584e267")],
    price_label: "On request",
    featured: false,
    in_stock: true,
    created_at: "2024-02-05T00:00:00Z",
  },
  {
    id: "prod-15",
    slug: "dreamcloud-orthopedic-mattress",
    name: "DreamCloud Orthopedic Mattress",
    category_slug: "mattresses",
    short_description: "Multi-layer orthopedic mattress.",
    description:
      "Engineered for spinal support, the DreamCloud mattress layers high-resilience foam over a pocketed spring core for balanced comfort and durability.",
    material: "Pocketed springs, HR foam, quilted knit cover",
    dimensions: "Available in Single, Queen & King",
    colours: ["White"],
    images: [img("photo-1631049307264-da0ec9d70304"), img("photo-1522708323590-d24dbb6b0267")],
    price_label: "On request",
    featured: true,
    in_stock: true,
    created_at: "2024-02-07T00:00:00Z",
  },
  {
    id: "prod-16",
    slug: "cloudrest-memory-foam-mattress",
    name: "CloudRest Memory Foam Mattress",
    category_slug: "mattresses",
    short_description: "Pressure-relieving memory foam.",
    description:
      "The CloudRest contours to your body with premium memory foam and a cooling gel layer for a cool, undisturbed night's sleep.",
    material: "Memory foam, cooling gel layer, breathable cover",
    dimensions: "Available in Single, Queen & King",
    colours: ["White"],
    images: [img("photo-1631049307264-da0ec9d70304"), img("photo-1505693416388-ac5ce068fe85")],
    price_label: "On request",
    featured: false,
    in_stock: true,
    created_at: "2024-02-09T00:00:00Z",
  },
];

export const sampleBanners: Banner[] = [
  {
    id: "banner-1",
    title: "Timeless Furniture, Crafted in Kerala",
    subtitle:
      "Discover premium sofas, beds and dining collections at Matha Furniture, Thiruvananthapuram.",
    image: img("photo-1618220179428-22790b461013", 2000),
    cta_label: "Explore Collection",
    cta_href: "/products",
    active: true,
    sort_order: 1,
  },
  {
    id: "banner-2",
    title: "Elevate Every Room",
    subtitle: "From cozy living rooms to elegant dining spaces — designed for modern homes.",
    image: img("photo-1616137466211-f939a420be84", 2000),
    cta_label: "Visit Our Showrooms",
    cta_href: "/contact",
    active: true,
    sort_order: 2,
  },
];

export const sampleTestimonials: Testimonial[] = [
  {
    id: "t-1",
    name: "Anjali Menon",
    location: "Kesavadasapuram",
    rating: 5,
    quote:
      "The quality of our new sofa is exceptional. The team helped us pick the perfect fabric and delivery was on time. Highly recommended!",
    avatar: img("photo-1494790108377-be9c29b29330", 200),
    approved: true,
    created_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "t-2",
    name: "Rahul Nair",
    location: "Pattom",
    rating: 5,
    quote:
      "Bought a complete bedroom set from Matha Furniture. Beautiful craftsmanship and honest pricing. Very happy with the experience.",
    avatar: img("photo-1500648767791-00dcc994a43e", 200),
    approved: true,
    created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "t-3",
    name: "Fathima Rasheed",
    location: "Thiruvananthapuram",
    rating: 5,
    quote:
      "Their dining table is the centrepiece of our home now. Excellent service and great after-sales support.",
    avatar: img("photo-1438761681033-6461ffad8d80", 200),
    approved: true,
    created_at: "2024-01-12T00:00:00Z",
  },
];

export const sampleGallery: GalleryImage[] = [
  { id: "g-1", title: "Modern Living Room Setup", image: img("photo-1616137466211-f939a420be84"), category: "Living Room", sort_order: 1 },
  { id: "g-2", title: "Elegant Master Bedroom", image: img("photo-1505693416388-ac5ce068fe85"), category: "Bedroom", sort_order: 2 },
  { id: "g-3", title: "Family Dining Space", image: img("photo-1617806118233-18e1de247200"), category: "Dining", sort_order: 3 },
  { id: "g-4", title: "Home Office Corner", image: img("photo-1524758631624-e2822e304c36"), category: "Office", sort_order: 4 },
  { id: "g-5", title: "Cozy Reading Nook", image: img("photo-1567538096630-e0c55bd6374c"), category: "Living Room", sort_order: 5 },
  { id: "g-6", title: "Contemporary TV Wall", image: img("photo-1586023492125-27b2c045efd7"), category: "Living Room", sort_order: 6 },
  { id: "g-7", title: "Walk-in Wardrobe", image: img("photo-1595428774223-ef52624120d2"), category: "Bedroom", sort_order: 7 },
  { id: "g-8", title: "Luxury Sectional Lounge", image: img("photo-1567016432779-094069958ea5"), category: "Living Room", sort_order: 8 },
];

export const sampleContact: ContactInfo = {
  id: "contact-1",
  business_name: "Matha Furniture",
  email: "hello@mathafurniture.com",
  phone: "+91 99999 99999",
  whatsapp: "919999999999",
  instagram: "https://instagram.com/mathafurniture",
  facebook: "https://facebook.com/mathafurniture",
  locations: [
    {
      name: "Matha Furniture - Kesavadasapuram",
      address: "Kesavadasapuram, Pattom P.O, Thiruvananthapuram, Kerala 695004",
      phone: "+91 99999 99999",
      hours: "Mon - Sat: 9:30 AM - 8:30 PM | Sun: 10:00 AM - 6:00 PM",
      map_embed:
        "https://www.google.com/maps?q=Kesavadasapuram,Thiruvananthapuram&output=embed",
    },
    {
      name: "Matha Furniture - Pattom",
      address: "Pattom, Thiruvananthapuram, Kerala 695004",
      phone: "+91 88888 88888",
      hours: "Mon - Sat: 9:30 AM - 8:30 PM | Sun: 10:00 AM - 6:00 PM",
      map_embed: "https://www.google.com/maps?q=Pattom,Thiruvananthapuram&output=embed",
    },
  ],
};

// silence unused-in-some-builds warning for shared colour palette
export const defaultColours = colours;
